### ISSUE TITLE
Encampment Chair Wrong mats

### ISSUE THREAD

**Issue by za-x-az** [yamamushi/dumap#103]
Hi, the newly added chair has crazy wrong mats.

as u can see in the first I'm that's the mats of the nano crafter, an assembler take 2X and make 2X
The second img is the website it uses 10 times too many Basic Fixation, and thus 75 and not 2 Polycarbonate Plastic pr chair
![image](https://user-images.githubusercontent.com/45720278/95666948-5e7d4a00-0b5f-11eb-8093-16b6232158b2.png)
![image](https://user-images.githubusercontent.com/45720278/95666960-8ec4e880-0b5f-11eb-9fe4-1a2114782da7.png)

**Comment by Allen-Tainia** [comment]
Fixations are made in batches of 10 and products are made in batches of 75 (skills notwithstanding). In order to make 1 fixation you have to make 10. In order to make 1 plastic, you have to make 75. This calculator shows everything you need to make an item, which includes the materials you need to make the entire batch. You can't make a partial batch.
